# meta_train.py — build Meta-TAF population models from completed BOforUnity runs.
#
# Offline tool (run by the researcher, never by participants). It converts each finished
# run's ObservationsPerEvaluation.csv into one "source artifact" pair understood by the
# Meta-TAF backend / openbo:
#
#     <out>/trajectories/<name>.json   x_values (n,d) in [0,1]^d, y_values (n,M) in
#                                      [-1,1] maximization, pareto_front (P,M)
#     <out>/gp_states/<name>.json      per-objective GP hyperparameters + the study
#                                      frame + provenance
#
# Everything is normalized through bo_normalize (the exact transform the live backends
# apply), and the study frame is stamped into every artifact so the runtime can refuse
# sources whose bounds or minimize flags do not match the live study -- a mismatch there
# would silently transfer a rescaled or inverted response surface.
#
# Usage:
#   python meta_train.py --frame frame.json --out ../MetaSources/MyStudy \
#       --source-type human --y-calibration measured runDir1 runDir2 ...
#
# --source-type and --y-calibration are REQUIRED provenance stamps (who produced the
# objective values, and whether they were measured from real participants/systems or
# generated by a model such as LLM personas). They are written into every artifact and
# copied into each live run's MetaSourcesUsed audit trail -- label them honestly.
#
# Each artifact is named after its run's path tail (<participant>_<condition>_<run>), never
# after its position on the command line, and a run already in --out keeps the name it has
# there (also an index-prefixed one from an older version), so rebuilding into the same --out
# finds the same names; existing artifacts are only replaced with --force. After every build the folder's
# population manifest (population.json: names, hashes, frame digest) is rewritten; the
# runtime refuses to start when the population it loads differs from it. --dry-run checks
# names and runs without fitting or writing; --manifest-only rewrites just the manifest.
#
# frame.json mirrors the Unity configuration (every objective needs its "minimize" flag):
#   {
#     "parameters": [{"key": "speed", "low": 0.0, "high": 10.0}, ...],
#     "objectives": [{"key": "comfort", "low": 0.0, "high": 100.0, "minimize": 0}, ...]
#   }
#
# Requires the full stack (openbo + botorch); see docs/meta-taf-student-guide.md.

import argparse
import datetime
import hashlib
import json
import math
import os
import re
import shutil
import sys
import tempfile
import time

import numpy as np
import pandas as pd

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import bo_normalize
import meta_fingerprint

# GP mean vs data sanity threshold (normalized objective units, range is [-1, 1]).
FIT_RESIDUAL_WARN = 0.3

# Objectives live in [-1, 1] maximization; the runtime's hypervolume reference point is
# HYPERVOLUME_REFERENCE_VALUE in every objective (shared with mobo.py / meta_mobo_runtime.py).
REF_POINT_VALUE = bo_normalize.HYPERVOLUME_REFERENCE_VALUE

# GP fit restarts per objective; see fit_per_objective_hyperparameters.
N_FIT_RESTARTS = 8

# The population manifest in --out; meta_mobo_runtime.py reads the same file name.
MANIFEST_FILENAME = "population.json"
MANIFEST_SCHEMA_VERSION = 1

# os.replace of a published file fails on Windows while another process holds it open (an
# editor, antivirus, a sync client); such holds are usually brief, so retry for this long.
REPLACE_RETRY_SEC = 5.0

# Leading columns of the runtime's MetaWeightsPerEvaluation.csv, which adds one column per
# source; a source named like one of them would duplicate a column.
WEIGHTS_LOG_COLUMNS = ("Iteration", "OptimizationStep", "TargetWeight", "DecayFactor")


def _pip_command():
    """pip for the interpreter running this script: Unity runs the backends in its own private
    environment, so a bare `python -m pip` would install into a different Python."""
    exe = sys.executable or "python"
    return (f'"{exe}"' if " " in exe else exe) + " -m pip"


def _import_stack():
    try:
        import torch
        from botorch.fit import fit_gpytorch_mll
        from botorch.models import SingleTaskGP
        from botorch.models.transforms.outcome import Standardize
        from gpytorch.kernels import MaternKernel, ScaleKernel
        from gpytorch.mlls import ExactMarginalLogLikelihood

        from openbo.optimizers.mobo_botorch import pareto_front
        from openbo.optimizers.mobo_taf import _load_mo_source_surrogates
    except ImportError as e:
        raise SystemExit(
            f"meta_train.py needs torch/botorch/gpytorch and the openbo fork installed ({e}).\n"
            "Install openbo with:\n"
            f"    {_pip_command()} install \"open-bo @ git+https://github.com/M-Colley/openbo@main\"\n"
            f"or, from a local clone:  {_pip_command()} install -e path/to/openbo"
        )
    return (torch, fit_gpytorch_mll, SingleTaskGP, Standardize, MaternKernel,
            ScaleKernel, ExactMarginalLogLikelihood, pareto_front, _load_mo_source_surrogates)


def _frame_entry(entry, kind, index, fields):
    """One frame.json entry as a dict holding ``fields``, or SystemExit naming what is missing."""
    if not isinstance(entry, dict):
        raise SystemExit(f"frame.json: {kind} {index} must be an object, got {entry!r}.")
    missing = [field for field in fields if field not in entry]
    if missing:
        label = f"{kind} '{entry['key']}'" if "key" in entry else f"{kind} {index}"
        raise SystemExit(f"frame.json: {label} lacks {missing}.")
    return entry


def _minimize_flag(entry):
    """The objective's explicit minimize flag (0/1 or false/true).

    Required, like in the Unity init message: a silent default of 0 turned a minimized
    objective that someone forgot to flag into a maximized one, i.e. an exactly inverted
    source whose frame stamp then matched any study that made the same omission.
    """
    flag = entry["minimize"]
    if isinstance(flag, bool):
        return int(flag)
    if isinstance(flag, (int, float)) and flag in (0, 1):
        return int(flag)
    raise SystemExit(
        f"frame.json: objective '{entry['key']}' needs \"minimize\": 0 or 1, got {flag!r}."
    )


def load_frame(frame_path):
    with open(frame_path, "r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise SystemExit("frame.json must be an object with 'parameters' and 'objectives'.")
    params = payload.get("parameters") or []
    objs = payload.get("objectives") or []
    if not params or not objs:
        raise SystemExit("frame.json must define non-empty 'parameters' and 'objectives'.")
    params = [_frame_entry(p, "parameter", i, ("key", "low", "high")) for i, p in enumerate(params)]
    objs = [_frame_entry(o, "objective", i, ("key", "low", "high", "minimize")) for i, o in enumerate(objs)]
    parameter_names = [str(p["key"]) for p in params]
    parameters_info = [(float(p["low"]), float(p["high"])) for p in params]
    objective_names = [str(o["key"]) for o in objs]
    objectives_info = [(float(o["low"]), float(o["high"]), _minimize_flag(o)) for o in objs]
    if len(objective_names) < 2:
        raise SystemExit("Meta-TAF sources are multi-objective: define at least 2 objectives.")
    for name, bounds in zip(parameter_names + objective_names, parameters_info + objectives_info):
        lo, hi = bounds[0], bounds[1]
        if not (math.isfinite(lo) and math.isfinite(hi)) or hi < lo:
            raise SystemExit(f"frame.json: '{name}' needs finite bounds with low <= high, got [{lo}, {hi}].")
    frame = meta_fingerprint.canonical_frame(
        parameter_names, parameters_info, objective_names, objectives_info
    )
    return frame, parameter_names, parameters_info, objective_names, objectives_info


def sanitize_name(name):
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(name)).strip("_.")
    return cleaned or "source"


LOG_FILENAME = "ObservationsPerEvaluation.csv"


def run_identity(run_path):
    """The run a path refers to: the run folder for '<run>/ObservationsPerEvaluation.csv',
    otherwise the absolute path itself (a run folder, or a CSV under another name)."""
    path = os.path.normpath(os.path.abspath(str(run_path)))
    if os.path.basename(path).lower() == LOG_FILENAME.lower():
        path = os.path.dirname(path)
    return path


def _same_file(path_a, path_b):
    """Whether two existing paths are one file or folder; None when that cannot be told
    (a path is missing, or the file system reports inode 0 for everything, as some network
    file systems do -- os.path.samefile would then call every pair the same)."""
    try:
        stat_a, stat_b = os.stat(path_a), os.stat(path_b)
    except (OSError, ValueError):
        return None
    if not (stat_a.st_ino and stat_b.st_ino):
        return None
    return os.path.samestat(stat_a, stat_b)


def same_run(path_a, path_b):
    """True when two paths (run folder or its CSV, any spelling) name the same run.

    Paths that exist are compared by file identity, which also catches another spelling on a
    case-insensitive file system (normcase folds case on Windows only, not on macOS);
    otherwise, e.g. for a run_path recorded on another machine, by the normalized path.
    """
    a, b = run_identity(path_a), run_identity(path_b)
    same = _same_file(a, b)
    if same is not None:
        return same

    def key(path):
        return os.path.normcase(os.path.realpath(path))
    return key(a) == key(b)


def path_hash(run_path):
    """Short, stable hash of a run's absolute path (disambiguates colliding names)."""
    key = os.path.normcase(os.path.realpath(run_identity(run_path)))
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:8]


def derive_name(run_path):
    """Artifact name from the run's path tail: '<participant>_<condition>_<run>'.

    Depends on the path only. The former '<index>_' prefix tied the name to the run's
    position on the command line, so rebuilding a population into the same --out with one
    more (or reordered) run published renamed duplicates next to the existing artifacts and
    the duplicated participants counted twice in every later run. A CSV path is named after
    its run folder ('<run>/ObservationsPerEvaluation.csv'), or after its own file name when
    the CSV is named otherwise, so the participant folder stays in the name.
    """
    path = run_identity(run_path)
    parts = [p for p in path.split(os.sep) if p and not p.endswith(":")]
    if parts and os.path.splitext(parts[-1])[1].lower() == ".csv":
        parts[-1] = os.path.splitext(parts[-1])[0]
    return sanitize_name("_".join(parts[-3:]))


def existing_artifacts(out_dir):
    """{name: provenance} of the artifacts already in ``out_dir`` (provenance {} if unreadable)."""
    gp_dir = os.path.join(out_dir, "gp_states")
    if not os.path.isdir(gp_dir):
        return {}
    found = {}
    for fname in sorted(os.listdir(gp_dir)):
        if not fname.endswith(".json") or fname.startswith("."):
            continue  # also macOS AppleDouble '._<name>.json' files
        provenance = {}
        try:
            with open(os.path.join(gp_dir, fname), "r", encoding="utf-8") as f:
                payload = json.load(f)
            if isinstance(payload, dict) and isinstance(payload.get("provenance"), dict):
                provenance = payload["provenance"]
        except (OSError, ValueError):
            pass
        found[fname[:-len(".json")]] = provenance
    return found


def stored_observations(out_dir, names):
    """{name: (x_values, y_values)} of the artifacts in ``out_dir`` whose trajectory reads."""
    found = {}
    for name in names:
        try:
            with open(os.path.join(out_dir, "trajectories", f"{name}.json"), "r", encoding="utf-8") as f:
                payload = json.load(f)
            found[name] = (np.asarray(payload["x_values"], dtype=np.float64),
                           np.asarray(payload["y_values"], dtype=np.float64))
        except (OSError, ValueError, KeyError, TypeError):
            continue
    return found


def names_holding_run(run, existing, observations=None, stored=None):
    """Names in ``out_dir`` whose artifact was built from ``run``.

    By the provenance run_path, or -- for a name derived from the same path tail (plain,
    hashed, or an older version's '<index>_<tail>') -- by identical normalized observations
    (``observations``: {run: (x_unit, y_norm)}, ``stored``: stored_observations): a
    population built on another machine, or before the project folder moved, records another
    absolute path for the same run, which would otherwise be built a second time under a
    hashed name.
    """
    held = {
        name for name, provenance in existing.items()
        if isinstance(provenance.get("run_path"), str) and same_run(provenance["run_path"], run)
    }
    mine = (observations or {}).get(run)
    if mine is not None:
        tail = re.escape(derive_name(run))
        held.update(
            name for name, theirs in (stored or {}).items()
            if re.fullmatch(rf"(\d+_)?{tail}(-[0-9a-f]{{8}})?", name)
            and all(np.shape(a) == np.shape(b) and np.array_equal(a, b) for a, b in zip(mine, theirs))
        )
    return sorted(held)


def assign_names(runs, explicit_names, existing, observations=None, stored=None):
    """One artifact name per run: explicit, else the path tail plus a path hash on collision.

    A derived name collides when another run of this call derives the same tail, or when
    ``out_dir`` already holds that name for a different run. A run already in ``out_dir``
    keeps the name it has there -- its plain or hashed name, or the index-prefixed name
    ('00_p01_main_run') an older meta_train.py gave it, also when it was built from another
    path (names_holding_run) -- so the names of a population do not depend on which runs are
    rebuilt together, and rebuilding a folder built by an older version, on another machine
    or before the project moved, with one more run adds that run only instead of a second
    copy of every other.
    """
    if explicit_names is not None:
        return [sanitize_name(n) for n in explicit_names]
    tails = [derive_name(run) for run in runs]
    names = []
    for run, tail in zip(runs, tails):
        hashed = f"{tail}-{path_hash(run)}"
        held = names_holding_run(run, existing, observations, stored)
        if held:
            names.append(tail if tail in held else hashed if hashed in held else held[0])
        elif tail in existing:
            names.append(hashed)  # the plain name belongs to another run
        elif hashed in existing:
            names.append(hashed)  # built earlier next to a run with the same tail
        else:
            clash = any(t == tail and not same_run(other, run) for other, t in zip(runs, tails))
            names.append(hashed if clash else tail)
    return names


def same_run_other_names(run, name, existing, out_dir=None, observations=None, stored=None):
    """Names in ``out_dir`` that hold this same run under a name other than ``name``.

    A name whose gp_state is the very file of ``name`` (another spelling of it on a
    case-insensitive file system) is the same artifact, not a second copy.
    """
    others = [other for other in names_holding_run(run, existing, observations, stored)
              if other != name]
    if out_dir is None:
        return others
    mine = os.path.join(out_dir, "gp_states", f"{name}.json")
    return [other for other in others
            if not _same_file(mine, os.path.join(out_dir, "gp_states", f"{other}.json"))]


def read_run_csv(run_path):
    csv_path = run_path
    if os.path.isdir(run_path):
        csv_path = os.path.join(run_path, "ObservationsPerEvaluation.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"No ObservationsPerEvaluation.csv under: {run_path}")
    return pd.read_csv(csv_path, delimiter=";", encoding="utf-8")


def normalize_param_column_strict(col, lo, hi, name):
    """Raw parameter column -> [0, 1], refusing any value outside the frame's raw bounds.

    bo_normalize.normalize_param_column falls back to "already normalized" for values that
    miss the raw bounds but lie in [0, 1] -- a warm-start convenience. ObservationsPerEvaluation.csv
    is raw by construction, so here that fallback would silently reinterpret a run recorded
    under DIFFERENT bounds (pilot [0, 1], frame.json [0.2, 0.8]: raw 0.05 became x = 0.05),
    and the frame stamp would then certify the distorted source. Values may overshoot the
    bounds only by the warm-start rounding tolerance (bo_normalize.raw_bounds_tolerance: half a
    unit of the third decimal, or 0.05% of a wider range, for logs rounded to few decimals) and
    are clipped back.
    """
    col = np.asarray(col, dtype=np.float64)
    tol = bo_normalize.raw_bounds_tolerance(lo, hi)
    outside = (col < lo - tol) | (col > hi + tol)
    if np.any(outside):
        bad = np.unique(col[outside])
        shown = ", ".join(format(float(v), ".10g") for v in bad[:5]) + (", ..." if bad.size > 5 else "")
        raise ValueError(
            f"Parameter column '{name}': {int(np.count_nonzero(outside))} value(s) outside the "
            f"frame bounds [{lo:.10g}, {hi:.10g}]: {shown}. The run was not recorded with the "
            "bounds in frame.json (did the study bounds change?); refusing to rescale it."
        )
    # Clipped into the bounds, so normalize_param_column always takes its raw-units branch;
    # raw units are guaranteed here, so its raw-vs-normalized ambiguity notice would mislead.
    return bo_normalize.normalize_param_column(np.clip(col, lo, hi), lo, hi, warn=lambda _msg: None)


def extract_normalized_xy(df, parameter_names, parameters_info, objective_names, objectives_info):
    """Columns by NAME (never position), raw units -> the canonical frame."""
    if "Context" in df.columns:
        raise ValueError(
            "This run contains a 'Context' column (contextual optimization). Contextual "
            "runs cannot become Meta-TAF sources: the context dimension has no home in a "
            "context-free source model."
        )
    missing = [c for c in parameter_names + objective_names if c not in df.columns]
    if missing:
        raise ValueError(f"Run CSV is missing required column(s): {missing}")

    x_raw = df[parameter_names].apply(pd.to_numeric, errors="raise").to_numpy(dtype=np.float64)
    y_raw = df[objective_names].apply(pd.to_numeric, errors="raise").to_numpy(dtype=np.float64)
    if x_raw.shape[0] < 3:
        raise ValueError(f"Run has only {x_raw.shape[0]} rows; need at least 3 to fit a GP.")
    if not (np.all(np.isfinite(x_raw)) and np.all(np.isfinite(y_raw))):
        raise ValueError("Run CSV contains NaN/Inf values.")

    x_unit = np.zeros_like(x_raw)
    for j, (lo, hi) in enumerate(parameters_info):
        x_unit[:, j] = normalize_param_column_strict(x_raw[:, j], lo, hi, parameter_names[j])
    y_norm = np.zeros_like(y_raw)
    for j, (lo, hi, minflag) in enumerate(objectives_info):
        # ObservationsPerEvaluation.csv stores raw units by construction.
        y_norm[:, j] = bo_normalize.normalize_obj_column(y_raw[:, j], lo, hi, minflag, fmt="raw")
    return x_unit, y_norm


def is_finite_restart(score, entry):
    """True when a restart's score and every exported hyperparameter are finite numbers."""
    values = [score, entry["variance"], entry["noise"], entry["mean_constant"], *entry["lengthscale"]]
    return all(math.isfinite(float(v)) for v in values)


def fit_per_objective_hyperparameters(x_unit, y_norm, stack):
    """Fit one GP per objective and export hyperparameters the loader can replay.

    The kernel structure (ScaleKernel(Matern52) + Standardize outcome transform) is
    exactly what openbo's loader reconstructs, so exporting these values -- including
    the fitted constant mean -- and replaying them is a faithful round trip by
    construction.

    Each objective is fitted N_FIT_RESTARTS times and the restart with the highest
    marginal log-likelihood wins. A single fit attempt can land in a degenerate local
    optimum -- most commonly the "collapse to noise" solution (outputscale near 0 with
    the noise term absorbing the data variance), which turns the source into a flat,
    useless prior. Restart 0 keeps botorch's default initialization, so a clean single
    fit stays reachable unchanged; restarts 1+ perturb the starting hyperparameters
    from a deterministic per-(objective, restart) seed.

    Restarts are scored against ``gp.train_targets`` -- the Standardize-transformed
    targets that ``fit_gpytorch_mll`` itself maximizes -- never against the raw
    normalized y. The raw targets live on a different scale, and scoring on it is
    systematically biased toward exactly the degenerate high-noise fits the restarts
    exist to reject (low-variance raw targets look deceptively probable under wide,
    noisy marginals).
    """
    (torch, fit_gpytorch_mll, SingleTaskGP, Standardize, MaternKernel,
     ScaleKernel, ExactMarginalLogLikelihood, _, _) = stack

    x_t = torch.tensor(x_unit, dtype=torch.double)
    entries = []
    d = x_unit.shape[1]
    for j in range(y_norm.shape[1]):
        y_t = torch.tensor(y_norm[:, j:j + 1], dtype=torch.double)

        best_score = None
        best_entry = None
        failures = []

        for restart in range(N_FIT_RESTARTS):
            gp = SingleTaskGP(
                x_t, y_t,
                covar_module=ScaleKernel(MaternKernel(nu=2.5, ard_num_dims=d)),
                outcome_transform=Standardize(m=1),
            )
            if restart > 0:
                # Deterministically perturbed starting point so this restart explores
                # a different likelihood basin than botorch's default init (restart 0).
                gen = torch.Generator().manual_seed(7919 * j + restart)
                with torch.no_grad():
                    gp.covar_module.base_kernel.lengthscale = torch.exp(
                        torch.randn(d, generator=gen, dtype=torch.double)
                    )
                    gp.covar_module.outputscale = torch.exp(
                        torch.randn(1, generator=gen, dtype=torch.double) * 0.5
                    )
                    gp.likelihood.noise = torch.exp(
                        torch.randn(1, generator=gen, dtype=torch.double) - 2.0
                    )

            mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
            try:
                fit_gpytorch_mll(mll)
            except Exception as e:  # a failed restart is skipped, not fatal
                failures.append(f"restart {restart}: {e}")
                continue

            # fit_gpytorch_mll() leaves the model in eval mode, where gp(x_t) is the
            # posterior conditioned on the training data -- not the training marginal
            # the fit maximized. Score in train mode against gp.train_targets.
            gp.train()
            mll.train()
            with torch.no_grad():
                score = float(mll(gp(x_t), gp.train_targets).sum())
            entry = {
                "kernel_type": "matern52",
                "lengthscale": [float(v) for v in
                                gp.covar_module.base_kernel.lengthscale.detach().reshape(-1)],
                "variance": float(gp.covar_module.outputscale.detach()),
                "noise": float(gp.likelihood.noise.detach().reshape(-1)[0]),
                "mean_constant": float(gp.mean_module.constant.detach().reshape(-1)[0]),
                "standardize_targets": True,
                "optimize_noise": True,
            }

            # NaN never compares greater, so a NaN score on the FIRST successful restart
            # would otherwise stay "best" for good; non-finite hyperparameters would replay
            # as a NaN surface. Either way this restart counts as failed.
            if not is_finite_restart(score, entry):
                failures.append(f"restart {restart}: non-finite marginal likelihood or hyperparameters")
                continue
            if best_score is None or score > best_score:
                best_score = score
                best_entry = entry

        if best_entry is None:
            raise RuntimeError(
                f"All {N_FIT_RESTARTS} GP fit attempts failed for objective column {j}: "
                + "; ".join(failures)
            )
        entries.append(best_entry)
    return entries


def check_dominates_reference(y_norm):
    """Refuse a run none of whose points strictly dominates the hypervolume reference point.

    Such a source can never contribute hypervolume improvement and the runtime would drop
    it; the check surfaces that here instead of mid-study. Some point dominates the
    reference exactly when some Pareto point does, so the raw rows suffice.
    """
    if not np.any(np.all(np.asarray(y_norm, dtype=np.float64) > REF_POINT_VALUE, axis=1)):
        raise ValueError(
            f"no observation strictly dominates the hypervolume reference point "
            f"({REF_POINT_VALUE:g} in every objective of the normalized [-1, 1] space); this "
            "run would contribute zero hypervolume as a population model. Check the run's "
            "objective columns and the frame's objective bounds."
        )


def write_artifact(out_dir, name, x_unit, y_norm, gp_entries, frame, run_path,
                   source_type, y_calibration, stack):
    (_, _, _, _, _, _, _, pareto_front, load_sources) = stack

    check_dominates_reference(y_norm)
    front = np.asarray(pareto_front(y_norm), dtype=np.float64)

    trajectory = {
        "x_values": x_unit.tolist(),
        "y_values": y_norm.tolist(),
        "pareto_front": front.tolist(),
    }
    gp_payload = {
        "gp_state": {"objectives": gp_entries},
        "frame": frame,
        "provenance": {
            "schema_version": 1,
            # Caller-declared, never guessed: false "human/measured" stamps would
            # poison every downstream run's MetaSourcesUsed audit trail.
            "source_type": source_type,
            "y_calibration": y_calibration,
            "generator": "Assets/StreamingAssets/BOData/BayesianOptimization/meta_train.py",
            "created_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "run_path": os.path.abspath(str(run_path)),
            "n_observations": int(x_unit.shape[0]),
        },
    }
    # Self-check BEFORE publishing. The pair is written into a private scratch folder inside
    # out_dir (same volume, so the final os.replace calls are atomic), reloaded there through
    # the SAME loader the runtime uses, and its replayed posterior mean compared against the
    # data it was fitted on (a large residual means the artifact does not reproduce the run it
    # claims to represent). Only an artifact that passes is moved into gp_states/ +
    # trajectories/: a failed one leaves nothing behind that the runtime would stage and then
    # have to drop. The scratch name starts with "." so Unity's asset importer ignores it.
    os.makedirs(out_dir, exist_ok=True)
    scratch = tempfile.mkdtemp(prefix=".meta_train_", dir=out_dir)
    try:
        scratch_traj = os.path.join(scratch, "trajectories", f"{name}.json")
        scratch_gp = os.path.join(scratch, "gp_states", f"{name}.json")
        os.makedirs(os.path.dirname(scratch_traj))
        os.makedirs(os.path.dirname(scratch_gp))
        _write_json(scratch_traj, trajectory)
        # The gp_state names the exact trajectory bytes it belongs to. The two files are
        # published by two replaces; if the second fails (Windows: the old gp_state held
        # open by an editor, antivirus or a sync client), the runtime sees the mismatch and
        # skips the pair instead of combining old hyperparameters with new data.
        gp_payload["provenance"]["trajectory_sha256"] = meta_fingerprint.artifact_sha256(scratch_traj)
        _write_json(scratch_gp, gp_payload, indent=1)

        sources = load_sources(scratch, expected_m=y_norm.shape[1], expected_d=x_unit.shape[1])
        match = [s for s in sources if s.name == name]
        if not match:
            raise RuntimeError(f"Self-check failed: artifact '{name}' did not load back.")
        mu = match[0].posterior_mean(x_unit)
        residual = float(np.max(np.abs(mu - y_norm)))
        if not math.isfinite(residual):
            raise RuntimeError(
                f"Self-check failed: artifact '{name}' replays a non-finite posterior mean."
            )
        gp_payload["provenance"]["fit_residual"] = residual
        _write_json(scratch_gp, gp_payload, indent=1)

        traj_dir = os.path.join(out_dir, "trajectories")
        gp_dir = os.path.join(out_dir, "gp_states")
        os.makedirs(traj_dir, exist_ok=True)
        os.makedirs(gp_dir, exist_ok=True)
        _publish_pair(scratch, scratch_traj, os.path.join(traj_dir, f"{name}.json"),
                      scratch_gp, os.path.join(gp_dir, f"{name}.json"))
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    return residual


def _publish_pair(scratch, scratch_traj, traj_path, scratch_gp, gp_path):
    """Move a checked pair into place: trajectory first, then gp_state.

    The runtime discovers sources through gp_states/, so a crash between the two replaces
    leaves at most a trajectory next to its previous gp_state, which the trajectory stamp
    exposes. When the gp_state cannot be replaced, the previous trajectory is put back, so a
    rebuild with --force that fails leaves the previous pair as it was.
    """
    backup = None
    if os.path.exists(traj_path):
        backup = os.path.join(scratch, "previous_trajectory.json")
        shutil.copyfile(traj_path, backup)
    _replace_with_retry(scratch_traj, traj_path)
    try:
        _replace_with_retry(scratch_gp, gp_path)
    except OSError as e:
        restored = False
        try:
            if backup is not None:
                _replace_with_retry(backup, traj_path)
            else:
                os.remove(traj_path)
            restored = True
        except OSError:
            pass
        if restored:
            raise OSError(
                f"could not replace {gp_path} ({e}); the previous artifact pair was left as it "
                "was. Close the program holding the file and run meta_train.py again."
            ) from e
        raise OSError(
            f"could not replace {gp_path} ({e}) after the new trajectory was published, and "
            "the previous trajectory could not be restored either. The runtime skips this "
            "source (its gp_state no longer matches the trajectory); close the program "
            "holding the files and rebuild it with --force."
        ) from e


def _replace_with_retry(src, dst, retry_sec=None):
    """os.replace, retried with backoff while ``dst`` is held by another process."""
    deadline = time.monotonic() + (REPLACE_RETRY_SEC if retry_sec is None else retry_sec)
    delay = 0.05
    while True:
        try:
            os.replace(src, dst)
            return
        except OSError:
            if time.monotonic() + delay > deadline:
                raise
            time.sleep(delay)
            delay = min(2 * delay, 1.0)


def _write_json(path, payload, indent=None):
    # allow_nan=False: a NaN/Inf that slipped through is an error, never a non-JSON artifact.
    # fsync before the caller's os.replace: otherwise a power loss right after publishing can
    # leave a renamed but empty file on some file systems. newline="\n": the same bytes on
    # every OS (Windows text mode wrote CRLF), so the hashes in population.json are the plain
    # file hashes wherever the population was built.
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, indent=indent, allow_nan=False)
        f.flush()
        os.fsync(f.fileno())


def build_manifest(out_dir, frame):
    """The population in ``out_dir`` as the runtime will load it: ``(manifest, warnings)``.

    Lists every artifact pair whose frame matches ``frame`` and whose gp_state's trajectory
    stamp (if any) matches its trajectory, with the SHA-256 of both files. Pairs the runtime
    would skip are left out with a warning, so the manifest describes the loaded set.
    """
    gp_dir = os.path.join(out_dir, "gp_states")
    traj_dir = os.path.join(out_dir, "trajectories")
    warnings_out = []
    entries = []
    names = sorted(existing_artifacts(out_dir))
    for name in names:
        gp_path = os.path.join(gp_dir, f"{name}.json")
        traj_path = os.path.join(traj_dir, f"{name}.json")
        if not os.path.isfile(traj_path):
            warnings_out.append(f"'{name}' has no trajectory file; not part of the population")
            continue
        try:
            with open(gp_path, "r", encoding="utf-8") as f:
                payload = json.load(f)
            if not isinstance(payload, dict):
                raise ValueError("gp_state is not a JSON object")
            traj_sha = meta_fingerprint.artifact_sha256(traj_path)
            gp_sha = meta_fingerprint.artifact_sha256(gp_path)
        except (OSError, ValueError) as e:
            warnings_out.append(f"'{name}' is unreadable ({e}); not part of the population")
            continue
        diffs = meta_fingerprint.frame_differences(frame, payload.get("frame"))
        if diffs:
            warnings_out.append(
                f"'{name}' was built for another frame ({'; '.join(diffs)}); the runtime "
                "rejects it, so it is not part of the population"
            )
            continue
        provenance = payload.get("provenance") if isinstance(payload.get("provenance"), dict) else {}
        stamp = provenance.get("trajectory_sha256")
        if stamp is not None and stamp != traj_sha:
            warnings_out.append(
                f"'{name}': its trajectory is not the one its gp_state was built with (a "
                "half-replaced pair); the runtime skips it. Rebuild it with --force"
            )
            continue
        entries.append({
            "name": name,
            "trajectory_sha256": traj_sha,
            "gp_state_sha256": gp_sha,
            "run_path": provenance.get("run_path"),
            "source_type": provenance.get("source_type"),
            "y_calibration": provenance.get("y_calibration"),
        })

    by_hash = {}
    for entry in entries:
        by_hash.setdefault(entry["trajectory_sha256"], []).append(entry["name"])
    for group in by_hash.values():
        if len(group) > 1:
            warnings_out.append(
                f"{group} hold identical trajectories (the same run under several names?); "
                "that run would count several times in the population. Delete all but one"
            )

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "generator": "Assets/StreamingAssets/BOData/BayesianOptimization/meta_train.py",
        "created_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "frame_digest": meta_fingerprint.frame_digest(frame),
        "frame": frame,
        "hypervolume_reference_value": REF_POINT_VALUE,
        "sources": entries,
    }
    return manifest, warnings_out


def write_manifest(out_dir, frame):
    """Rewrite ``out_dir``/population.json atomically; print and return the manifest."""
    manifest, warnings_out = build_manifest(out_dir, frame)
    for warning in warnings_out:
        print(f"[WARN] {warning}.")
    os.makedirs(out_dir, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".population_", suffix=".json", dir=out_dir)
    os.close(fd)
    try:
        _write_json(tmp_path, manifest, indent=1)
        _replace_with_retry(tmp_path, os.path.join(out_dir, MANIFEST_FILENAME))
    except BaseException:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise
    print(f"Population manifest {os.path.join(os.path.abspath(out_dir), MANIFEST_FILENAME)}: "
          f"{len(manifest['sources'])} source(s), frame digest {manifest['frame_digest']}.")
    return manifest


def build_parser():
    parser = argparse.ArgumentParser(
        description="Convert completed BOforUnity runs into Meta-TAF population models."
    )
    parser.add_argument("runs", nargs="*",
                        help="Run folders (containing ObservationsPerEvaluation.csv) or CSV paths.")
    parser.add_argument("--frame", required=True,
                        help="frame.json describing the study's parameters and objectives.")
    parser.add_argument("--out", required=True,
                        help="Output MetaSources directory (gp_states/ + trajectories/ + "
                             "population.json are created).")
    parser.add_argument("--name", action="append", default=None, metavar="NAME",
                        help="Explicit artifact name for the run at the same position; repeat "
                             "once per run (--name p01 --name p02). Default: the run's path "
                             "tail, e.g. 'p01_main_run'.")
    parser.add_argument("--names", nargs="+", default=None, metavar="NAMES",
                        help="Explicit artifact names as one comma-separated list "
                             "(--names p01,p02). Space-separated names still work after the "
                             "run paths.")
    parser.add_argument("--source-type", choices=["human", "llm-persona", "synthetic"],
                        help="Provenance stamp (required to build): who produced the "
                             "objective values in these runs. Written into every artifact "
                             "and copied into each live run's MetaSourcesUsed audit trail.")
    parser.add_argument("--y-calibration", choices=["measured", "generated"],
                        help="Provenance stamp (required to build): 'measured' = objectives "
                             "observed from real participants/systems; 'generated' = "
                             "model-produced ratings (e.g. LLM personas).")
    parser.add_argument("--force", action="store_true",
                        help="Rebuild artifacts that already exist in --out (they are kept "
                             "otherwise; rebuilding changes the population).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Check the frame, the runs and the artifact names and report what "
                             "would be written, without fitting or writing anything.")
    parser.add_argument("--manifest-only", action="store_true",
                        help="Only rewrite --out/population.json from the artifacts already "
                             "there (after removing or adding sources by hand, before the "
                             "study). Takes no run paths.")
    return parser


def explicit_names(parser, args):
    """Names from --name / --names (None when neither is given), validated against the runs."""
    if args.name is not None and args.names is not None:
        parser.error("use either --name (repeated) or --names, not both.")
    if args.name is not None:
        names = list(args.name)
    elif args.names is not None:
        tokens = list(args.names)
        if len(tokens) > 1 and "," in tokens[0]:
            # '--names a,b run1 run2': the comma list is one token, the rest are run paths.
            args.runs = list(args.runs) + tokens[1:]
            tokens = tokens[:1]
        names = [n.strip() for token in tokens for n in token.split(",") if n.strip()]
    else:
        return None
    if args.names is not None and not args.runs:
        # nargs: '--names a b run1 run2' put before the runs consumes the run paths as well.
        paths = [n for n in names if os.path.exists(n)]
        parser.error(
            "no run paths given. '--names' placed before the run paths takes them as names"
            + (f" (it took {paths})" if paths else "")
            + "; put --names after the run paths, or use --names a,b,c or --name per run."
        )
    if len(names) != len(args.runs):
        parser.error(f"got {len(names)} name(s) for {len(args.runs)} run(s); give one name per run.")
    sanitized = [sanitize_name(n) for n in names]
    if len(set(sanitized)) != len(sanitized):
        parser.error(f"artifact names must be distinct, got {sanitized}.")
    return names


def main(argv=None):
    parser = build_parser()
    # Intermixed: run paths may sit between options ('--name p01 run1 --name p02 run2');
    # plain parse_args stops collecting them at the first option.
    args = parser.parse_intermixed_args(argv)
    names = explicit_names(parser, args)

    if args.manifest_only:
        if args.runs or args.dry_run:
            parser.error("--manifest-only takes no run paths and no --dry-run.")
        frame = load_frame(args.frame)[0]
        write_manifest(args.out, frame)
        return
    if not args.runs:
        parser.error("no run paths given.")
    if args.source_type is None or args.y_calibration is None:
        parser.error("--source-type and --y-calibration are required provenance stamps.")
    for i, run in enumerate(args.runs):
        repeated = [other for other in args.runs[:i] if same_run(other, run)]
        if repeated:
            parser.error(f"run '{run}' is listed more than once (also as '{repeated[0]}').")

    frame, parameter_names, parameters_info, objective_names, objectives_info = load_frame(args.frame)
    print(f"Frame digest: {meta_fingerprint.frame_digest(frame)} "
          f"(d={frame['d']}, M={frame['M']})")

    existing = existing_artifacts(args.out)
    # A run's normalized observations identify it in --out even under another recorded path.
    observations = {}
    for run in args.runs:
        try:
            observations[run] = extract_normalized_xy(
                read_run_csv(run), parameter_names, parameters_info, objective_names, objectives_info
            )
        except (OSError, ValueError):
            pass  # reported as [SKIP] below
    stored = stored_observations(args.out, existing)
    planned = assign_names(args.runs, names, existing, observations, stored)
    stack = None if args.dry_run else _import_stack()

    written = []
    kept = []
    for run, name in zip(args.runs, planned):
        if name in WEIGHTS_LOG_COLUMNS:
            print(f"[SKIP] {run}: the name '{name}' is a column of MetaWeightsPerEvaluation.csv; "
                  "choose another --name.")
            continue
        for other in same_run_other_names(run, name, existing, args.out, observations, stored):
            print(f"[WARN] {run} is also in --out as '{other}'. Together with '{name}', this run "
                  f"counts twice in the population: delete gp_states/{other}.json and "
                  f"trajectories/{other}.json, then rewrite population.json with --manifest-only.")
        exists = any(os.path.exists(os.path.join(args.out, sub, f"{name}.json"))
                     for sub in ("gp_states", "trajectories"))
        if exists and not args.force:
            origin = existing.get(name, {}).get("run_path") or "unknown run"
            print(f"[KEEP] {name}: already in --out (built from {origin}); pass --force to rebuild it.")
            kept.append(name)
            continue
        try:
            df = read_run_csv(run)
            x_unit, y_norm = extract_normalized_xy(
                df, parameter_names, parameters_info, objective_names, objectives_info
            )
            if args.dry_run:
                check_dominates_reference(y_norm)
                action = "replace" if exists else "write"
                print(f"[DRY]  {name}: n={x_unit.shape[0]} from {run}; would {action} "
                      f"gp_states/{name}.json + trajectories/{name}.json")
                written.append(name)
                continue
            gp_entries = fit_per_objective_hyperparameters(x_unit, y_norm, stack)
            residual = write_artifact(args.out, name, x_unit, y_norm, gp_entries, frame, run,
                                      args.source_type, args.y_calibration, stack)
        except (OSError, ValueError, RuntimeError) as e:
            print(f"[SKIP] {run}: {e}")
            continue
        note = ""
        if residual > FIT_RESIDUAL_WARN:
            note = (f"  <-- WARNING: fit residual {residual:.3f} > {FIT_RESIDUAL_WARN}; "
                    "this model reproduces its own run poorly (very noisy data?)")
        print(f"[OK]   {name}: n={x_unit.shape[0]}, fit residual {residual:.4f}{note}")
        written.append(name)

    if args.dry_run:
        print(f"\nDry run: {len(written)} artifact(s) would be written, {len(kept)} kept; "
              "nothing was written.")
        return
    if not written:
        hint = (" Pass --force to rebuild the existing ones, or --manifest-only to (re)write "
                "the population manifest." if kept else "")
        raise SystemExit("No artifacts were written." + hint)
    print(f"\nWrote {len(written)} population model(s) to {os.path.abspath(args.out)}")
    write_manifest(args.out, frame)
    print("Point the BoForUnityManager 'Meta Source Dir' at this folder (or copy it into "
          "Assets/StreamingAssets/BOData/MetaSources/). Freeze it before the study: the "
          "runtime refuses to start when the loaded population differs from population.json.")


if __name__ == "__main__":
    main()
